name: Tag Publishing

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  IMAGE_NAME: ausbird/nswag-docker

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      # Github
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      # Semver
      - name: Get version
        id: semver
        uses: LykkeBusiness/get-semver-from-tag-action@v1.0.2
        with:
          tag: ${{ github.ref }}
      # Docker
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.IMAGE_NAME }}
          # generate Docker tags based on the following events/attributes
          tags: |
            latest
            v${{ steps.semver.outputs.non-prefixed }}
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}